In [8]:
import numpy as np

eig = np.linalg.eig

In [16]:
matrix = np.matrix
testmatrix = np.array([[1,2,3],[5,3,4],[7,2,3],[10,11,12],[5,4,1]])
#testmatrix = matrix([[1,2,3],[5,3,4],[7,2,3]])

In [94]:
testmatrix = (testmatrix - np.mean(testmatrix,axis=0))

In [95]:
covMat = testmatrix.T @ testmatrix

In [96]:
eigMat = eig(covMat)[1] 

In [99]:
(testmatrix - np.mean(testmatrix,axis=0)) @eigMat[:,0]

array([-4.56337492, -1.49993621, -1.85822103, 10.83438094, -2.91284877])

In [93]:
testmatrix

array([[ 1,  2,  3],
       [ 5,  3,  4],
       [ 7,  2,  3],
       [10, 11, 12],
       [ 5,  4,  1]])

In [100]:
testmatrix @ eigMat[:,1]

array([-2.93540239, -0.03606323,  2.32814886, -0.52733058,  1.17064734])

In [ ]:
print eig(testmatrix) #Eigenvalue와 Eigenvector가 모두 나온다

print eig(testmatrix)[0] #Eigenvalue 부분을 출력한다

print eig(testmatrix)[1] #Eigenvector 부분을 출력한다.

In [101]:
from sklearn.decomposition import PCA
pca = PCA(n_components=1) # 주성분을 몇개로 할지 결정
printcipalComponents = pca.fit_transform(testmatrix)

In [102]:
printcipalComponents

array([[-4.56337492],
       [-1.49993621],
       [-1.85822103],
       [10.83438094],
       [-2.91284877]])